# Python для DataScience
## Домашнее задание по уроку 2

In [1]:
import numpy as np

### Задания на повторение

1. Создать одномерный массив Numpy под названием `a` из 12 последовательных целых чисел от 12 до 24 невключительно.

In [3]:
a = np.arange(12,24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода `reshape` число -1.

In [4]:
np.reshape(a,(6,2))

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [5]:
np.reshape(a,(4,3))

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [6]:
np.reshape(a,(3,4))

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [7]:
np.reshape(a,(2,6))

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [8]:
np.reshape(a,(1,12))

array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

3. Создать 5 двумерных массивов разной формы из массива `a`. Использовать в аргументах метода `reshape` число -1 (в трех примерах — для обозначения числа столбцов, в двух — для строк).

In [11]:
np.reshape(a,(6,-1))

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [13]:
np.reshape(a,(4,-1))

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [14]:
np.reshape(a,(-1,4))

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [15]:
np.reshape(a,(-1,6))

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [16]:
np.reshape(a,(-1,12))

array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
##### Ответ: 
Можно. Если был массив 12x1, то стал 1x12 

5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [17]:
a = np.random.normal(loc=0, scale=1.0, size=(3,4))
a

array([[ 0.51660035, -0.70908652,  2.75867318, -0.17613449],
       [ 1.23598949,  1.15261938,  0.45298452, -0.52416749],
       [ 0.77042576,  0.97544441, -0.37002661,  1.31595317]])

In [23]:
a_ = a.reshape(1,-1)
a_

array([[ 0.51660035, -0.70908652,  2.75867318, -0.17613449,  1.23598949,
         1.15261938,  0.45298452, -0.52416749,  0.77042576,  0.97544441,
        -0.37002661,  1.31595317]])

In [25]:
a.size == a_.size

True

6. Создать массив `a`, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2. Создать массив `b`, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами `a` и `b`?

In [42]:
a = np.arange(20,0,-2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [52]:
b = np.arange(20,1,-2).reshape(-1,1)
b

array([[20],
       [18],
       [16],
       [14],
       [12],
       [10],
       [ 8],
       [ 6],
       [ 4],
       [ 2]])

Массив `a` является транспонированным массивом `b`

In [54]:
a == b.transpose()

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

7. Вертикально соединить массивы `a` и `b`. `a` — двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива `b`, состоящего из единиц.
Итоговый массив v должен иметь атрибут `size`, равный 10.

In [67]:
a = np.zeros((3,2))
b = np.ones((2,2))
v = np.vstack((a,b))
v, v.size

(array([[0., 0.],
        [0., 0.],
        [0., 0.],
        [1., 1.],
        [1., 1.]]), 10)

8. Создать одномерный массив `а`, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица `A` (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу `At` путем транспонирования матрицы `A`. Получить матрицу `B`, умножив матрицу `A` на матрицу `At` с помощью матричного умножения.
Какой размер имеет матрица `B`? Получится ли вычислить обратную матрицу для матрицы `B` и почему?

In [70]:
a = np.arange(0,12)
A = a.reshape(4,3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [73]:
At = A.transpose()
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [74]:
B = np.dot(A,At)
B, B.size

(array([[  5,  14,  23,  32],
        [ 14,  50,  86, 122],
        [ 23,  86, 149, 212],
        [ 32, 122, 212, 302]]), 16)

In [77]:
np.linalg.det(B)

0.0

Матрица `B` является вырожденной, так как ее определитель равен нулю. А значит, обратную матрицу вычислить невозможно.

9. Инициализируйте генератор случайных числе с помощью объекта `seed`, равного 42. Создайте одномерный массив `c`, составленный из последовательности 16-ти случайных целых чисел от 0 до 16 невключительно. Поменяйте его форму так, чтобы получилась квадратная матрица `C`. Получите матрицу `D`, поэлементно прибавив матрицу `B` из предыдущего вопроса к матрице `C`, умноженной на 10. Вычислите определитель, ранг и обратную матрицу `D_inv` для `D`.

In [90]:
np.random.seed(42)
c = np.random.randint(0, high=16, size=16)
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

In [92]:
C = c.reshape((4,4))
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [109]:
D = B + C *10
D

array([[ 65,  44, 143, 172],
       [114, 120, 206, 162],
       [ 83, 176, 169, 272],
       [132, 222, 282, 342]])

In [96]:
np.linalg.det(D), np.linalg.matrix_rank(D)

(-28511999.999999944, 4)

In [98]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
       [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
       [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
       [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]])

10. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные — к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C — в качестве источников данных, получите матрицу E размером 4x4. Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [114]:
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1
D_inv

array([[1., 1., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.]])

In [117]:
E = np.where(D_inv, B, C)
E

array([[  5,  14,  23,  14],
       [ 10,   7,  12, 122],
       [  6,   9,   2, 212],
       [ 32,  10, 212,   4]])

### Задание 1
Загрузите модуль `pyplot` библиотеки `matplotlib` с псевдонимом `plt`,
а также библиотеку `numpy` с псевдонимом `np`.

Примените магическую функцию `%matplotlib inline` для
отображения графиков в Jupyter Notebook и
настройки конфигурации ноутбука со значением 'svg' для
более четкого отображения графиков.

Создайте список под названием `x` с числами $1, 2, 3, 4, 5, 6, 7$
и список `y` с числами $3.5, 3.8, 4.2, 4.5, 5, 5.5, 7$.

С помощью функции `plot` постройте график, соединяющий линиями точки с горизонтальными координатами из списка `x`
и вертикальными - из списка `y`.

Затем в следующей ячейке постройте диаграмму рассеяния
(другие названия - диаграмма разброса, scatter plot).

### Задание 2
С помощью функции linspace из библиотеки Numpy создайте массив t из 51 числа от 0 до 10 включительно. <br/>
Создайте массив Numpy под названием f, содержащий косинусы элементов массива t.<br/>
Постройте линейную диаграмму, используя массив t для координат по горизонтали,
а массив f - для координат по вертикали. Лния графика должна быть зеленого цвета.<br/>
Выведите название диаграммы - 'График f(t)'.<br/>
Также добавьте названия для горизонтальной оси - 'Значения t'
и для вертикальной - 'Значения f'.<br/>
Ограничьте график по оси x значениями 0.5 и 9.5,
а по оси y - значениями -2.5 и 2.5.<br/>

### Задание *3
С помощью функции linspace библиотеки Numpy создайте массив x
из 51 числа от -3 до 3 включительно.

Создайте массивы y1, y2, y3, y4 по следующим формулам:

$y1 = x**2 \\
y2 = 2 * x + 0.5 \\
y3 = -3 * x - 1.5 \\
y4 = sin(x) $

Используя функцию subplots модуля matplotlib.pyplot,
создайте объект matplotlib.figure.Figure с названием fig
и массив объектов Axes под названием ax,
причем так, чтобы у вас было 4 отдельных графика в сетке,
состоящей из двух строк и двух столбцов.

В каждом графике массив x используется для координат по горизонтали.

В левом верхнем графике для координат по вертикали используйте y1,

в правом верхнем - y2, в левом нижнем - y3, в правом нижнем - y4.

Дайте название графикам: 'График y1', 'График y2' и т.д.

Для графика в левом верхнем углу установите границы по оси x от -5 до 5.

Установите размеры фигуры 8 дюймов по горизонтали и 6 дюймов по вертикали.

Вертикальные и горизонтальные зазоры между графиками должны составлять 0.3.

### Задание *4
В этом задании мы будем работать с датасетом, в котором приведены данные по мошенничеству с кредитными данными:
Credit Card Fraud Detection (информация об авторах: Andrea Dal Pozzolo, Olivier Caelen, Reid A. Johnson and Gianluca Bontempi. Calibrating Probability with Undersampling for Unbalanced Classification. In Symposium on Computational Intelligence and Data Mining (CIDM), IEEE, 2015).

Ознакомьтесь с описанием и скачайте датасет creditcard.csv.

Данный датасет является примером несбалансированных данных, так как мошеннические операции с картами встречаются реже обычных.

Импортруйте библиотеку Pandas, а также используйте для графиков стиль “fivethirtyeight”.

Посчитайте с помощью метода value_counts количество наблюдений для каждого значения целевой переменной Class и примените к полученным данным метод plot, чтобы построить столбчатую диаграмму. Затем постройте такую же диаграмму, используя логарифмический масштаб.

На следующем графике постройте две гистограммы по значениям признака V1 - одну для мошеннических транзакций (Class равен 1) и другую - для обычных (Class равен 0). Подберите значение аргумента density так, чтобы по вертикали графика было расположено не число наблюдений, а плотность распределения. Число бинов должно равняться 20 для обеих гистограмм, а коэффициент alpha сделайте равным 0.5, чтобы гистограммы были полупрозрачными и не загораживали друг друга. Создайте легенду с двумя значениями: “Class 0” и “Class 1”. Гистограмма обычных транзакций должна быть серого цвета, а мошеннических - красного. Горизонтальной оси дайте название “Class”.